name: Run Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ubuntu images already ship with the Android SDK under /usr/local/lib/android/sdk.
      - name: Verify Android SDK
        run: |
          if ! command -v sdkmanager > /dev/null; then
            echo "Android SDK not found. Use an image with the SDK preinstalled (e.g., ubuntu-latest) or install it using actions/setup-android." >&2
            exit 1
          fi

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests
        run: ./gradlew test --no-daemon